### ISSUE TITLE
MRAs for the bootlegs and the MCU protected games?

### ISSUE THREAD

**Issue by gyurco** [va7deo/ArmedF#5]
Hi!

I've ported this core to MiST:
https://github.com/gyurco/Mist_FPGA/tree/armedf/Arcade_MiST/Nichibutsu%20M68000%20Hardware

I had to rework a lot of things, mostly because the lack of BRAM required to move much more ROMs to SDRAM, but it was successful.
Also reworked the clockings, now only 2 synchronous clocks are used: a 24 MHz one, which can provide all the required 6MHz, 4MHz and 8MHz clock enables, and a 96 MHz one for the SDRAM and the sprite machine. The pipelining of the tilemap layers are changed from a 1-pixel delayed pipeline to a 1-character based one (it's more realistic to use a ROM in a 1/6 MHz speed than a 6MHz speed, it's also looks similar to other arcade PCBs, where tilemap RAM/ROM address and data lines are latched e.g. on the rising edge of hcnt[2] or hcnt[3]. Not speak about the already overused SDRAM.)
And factored out the PCB code from the MiSTer stuff, suitable to use on more FPGA boards.

I'd like to check the "B" Z80 and even work on the Intel MCU, but before I start to make MRAs as the first step, I would like to ask, if they're already exists.

Thanks,
György

**Comment by atrac17** [comment]
Check the dev folder. We are working on the z80 bootlegs, i8751, and additional stuff. This is still an alpha core. I sent an email and will speak with my counterpart when he gets back.

Thanks!
atrac17

**Comment by gyurco** [comment]
Thanks, I found them. I won't publish my work until you're ready.
